- name: Make servers Reboot instantly
  hosts: local
  gather_facts: true
  tasks:
    - name: Start Reboot
      ansible.builtin.reboot:
        msg: "ACHTUNG! This server is going to Reboot \
              Make sure u have saved ur work.\nYou have 0 seconds \n"
