- name: Boot listed servers thru Ethernet
  gather_facts: false
  hosts: local
  connection: local
  vars:
    macaddr: "{{ hostvars['local'].macaddress|default(mac|default('')) }}"
  tasks:
    - name: Send WakeOnLan
      community.general.wakeonlan:
        mac: '{{ macaddr }}'
      delegate_to: localhost
        # broadcast: 192.168.0.255

- name: Wait for server to Boot Up
  hosts: local
  gather_facts: false
  tasks:
    - name: Wait for Connection
      ansible.builtin.wait_for_connection:
        timeout: 60
